//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddresses
    {
        public byte CustomerAddressID { get; set; }
        public int CustomerID { get; set; }
        public byte AddressTypeID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
    
        public virtual AddressTypes AddressTypes { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
