//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipments()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int ShipmentID { get; set; }
        public int OrderID { get; set; }
        public System.DateTime ShipDate { get; set; }
        public byte ShippingCarrierID { get; set; }
        public string TrackingNumber { get; set; }
        public byte ShipmentStatusID { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual ShipmentStatus ShipmentStatus { get; set; }
        public virtual ShippingCarriers ShippingCarriers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
    }
}
