//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorProducts
    {
        public int ProductID { get; set; }
        public int VendorID { get; set; }
        public int QuantityInStock { get; set; }
        public decimal ProductCost { get; set; }
        public int ReorderLevel { get; set; }
        public int ReorderQuantity { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Vendors Vendors { get; set; }
    }
}
